# Standards: 1.2
---
- name: Restart alertmanager
  systemd:
    name: alertmanager
    state: restarted
    daemon_reload: True

- name: Restart alertmanager-oauth2
  systemd:
    name: alertmanager-oauth2
    state: restarted
    daemon_reload: yes

...
